export const FETCH_CATEGORIES ='FETCH_CATEGORIES';
export const SWITCH_CATEGORY='SWITCH_CATEGORY';
export const FETCH_MENU='FETCH_MENU';
export const ADD_ITEM='ADD_ITEM';
export const ADD_ORDER='ADD_ORDER';